### PR TITLE
travis, build matrix

### PR DESCRIPTION
**Pull request by fanatid**
I added [build matrix](http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) to `.travis.yml` but real problem that `npm` run `prepublish` for every build..

### CODE REVIEW

**Comment by fanatid** [comment]
faucet error, please restart travis tests

**Comment by dcousens** [comment]
@fanatid what is a build matrix?

**Comment by fanatid** [comment]
possible combinations of builds
before this commit you have 16 builds (4 versions of node_js * 4 value of TEST_SUITE)
with matrix.include and removed 2 values from env it will be 10 builds (4 versions of node_js * 2 value of TEST_SUITE + 2 matrix.include)

**Comment by dcousens** [comment]
I guess it is a reasonable assumption then the `standard` should never change across node versions,  as with the coverage.

**Comment by dcousens** [comment]
@fanatid could you reduce the `build_matrix` to only `standard`?  I think `coverage` is still worthwhile running on all versions.

**Comment by dcousens** [comment]
After that, this is good to merge.

**Comment by dcousens** [comment]
Also,  can you add `5.0.0` to the TRAVIS list of versions to test.

**Comment by fanatid** [comment]
I do this, but why you want specific version 4.0.0 and 5.0.0 not 4 and 5?

**Comment by dcousens** [comment]
@fanatid good question,  are they equivalent?

**Comment by dcousens** [comment]
If `4` is the equivalent of `^4.0.0`, then I'd prefer that

**Comment by fanatid** [comment]
Travis use nvm, so 4 mean last 4.x.x version, I also prefer this

**Comment by dcousens** [comment]
Sounds good :+1:

**Comment by dcousens** [comment]
Looks good, waiting on tests to pass now.

**Comment by dcousens** [comment]
Thanks @fanatid

**Pull request merged**
