### PR TITLE
Fix typeforce (EMCA 6 syntax) issues in v1.5

### PR DESCRIPTION
**Pull request by mdemri**

### CODE REVIEW

**Comment by dcousens** [comment]
What were the issues?
In any case, I'm happy to merge this, not sure why the tests are failing.  Might have to restart then.

**Comment by mdemri** [comment]
var/lib/jenkins/jobs/Test-Issue-MainNet/workspace/node_modules/colu/node_modules/hdwallet/node_modules/bitcoinjs-lib/node_modules/typeforce/lib/index.js:45
  Array(value) {
       ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/jobs/Test-Issue-MainNet/workspace/node_modules/colu/node_modules/hdwallet/node_modules/bitcoinjs-lib/src/address.js:3:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/jobs/Test-Issue-MainNet/workspace/node_modules/colu/node_modules/hdwallet/node_modules/bitcoinjs-lib/src/index.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by mdemri** [comment]
That's the exception i get

**Comment by mdemri** [comment]
ECMA 6 issues?

**Comment by williamcotton** [comment]
Yup, this is affecting me as well!

**Comment by Sjors** [comment]
Same here. Maybe go back to 1.3.*? That version worked fine and 1.4 is only two days old.

**Comment by williamcotton** [comment]
Quick fix:

I installed typeforce@1.3.2 at the root of my project and then reinstalled any modules with bitcoinjs-lib as a dependency... this way node matches the ^1.0.0 dep to the older typeforce module at the project root and doesn't bother installing this broken version.

**Comment by dcousens** [comment]
Sigh, sorry guys.  It seems latest version of babel assumes that that ES6 syntax is standard and it got published with that transpilation.  I'll fix this in typeforce ASAP, as that will be faster than fixing it here.

Reference https://github.com/dcousens/typeforce/issues/17

**Comment by dcousens** [comment]
Fixed in https://github.com/dcousens/typeforce/commit/2133cc00ed2f345476c46990f859fcb2cae4f95f

**Comment by dcousens** [comment]
I'm happy to have the discussion about dependency version locking,  however that comes with the other pitfalls such as missing critical bug fixes.

**Pull request closed without merging**
