### PR TITLE
Atomize examples to their own files

### PR DESCRIPTION
**Pull request by prahaladbelavadi**
Potential fix for #1044
Needs review from @afk11 and @dcousens

### CODE REVIEW

**Comment by dcousens** [comment]
I guess the question is,  is this format any clearer than the integration tests as is?

**Comment by prahaladbelavadi** [comment]
I think it would lower the barrier to entry as to those that would be interacting with this library.

I don't think people that are learning how to code would be able to absolve what's happening from the test cases. 
This would be similar to providing good developer resources/documentation for developers that are potentially going to be working on other applications on top of this library. 

By providing individual examples, they can try out their own stuff and see things functioning.

A personal motive for adding these examples is that being self taught, I was unable to grasp the context earlier from the test cases. 

I felt examples would've helped

**Comment by dcousens** [comment]
I'm not against this.
Do we do it for every example?

Could the same result be achieved without using `mocha` but still having `assert`s or some way to verify the outputs against something?

We simply don't want the behaviour of the examples to change.
Maybe even checking as a script target that `$(node examples/* | diff - expected.log) && true` could be helpful here.

**Comment by dcousens** [comment]
With the example links persistently becoming out of sync,  I think this is the only sane solution.

What if we put these examples ~~tests~~ under `/docs` instead?  (and still ran them as integration tests,  but made them distinctly separate)

**Comment by junderw** [comment]
Do we still want to do this? I could take it over.

**Comment by dcousens** [comment]
I think it's probably a good idea,  but emphasis on the examples being "verified"  is important IMHO.

**Comment by junderw** [comment]
Closing stale PR. If you'd like to re-open please let me know.

**Pull request closed without merging**
