### PR TITLE
Helperbit in "Projects utilizing BitcoinJS"

### PR DESCRIPTION
**Pull request by dakk**

### CODE REVIEW

**Comment by dcousens** [comment]
How/where is it using it `bitcoinjs-lib`?  OOI

**Comment by dakk** [comment]
The under-the-hood platform is atm only available for no-profit organization; bitcoinjs is used for multisig walleting, script parsing and more.

**Comment by dcousens** [comment]
@dakk can you rebase?

**Comment by dakk** [comment]
@dcousens I just rebased

**Comment by dcousens** [comment]
You merged,  not rebase

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/844

**Comment by dakk** [comment]
ok thanks; I merged because the README.md was different from the version I modified weeks ago

**Pull request closed without merging**
