### PR TITLE
[NO MERGE] Bitcoin Gold and Bitcoin Cash support on v3.3.0

### PR DESCRIPTION
**Pull request by lacksfish**
Feedback very welcome

### CODE REVIEW

**Comment by dcousens** [comment]
Does this supersede https://github.com/bitcoinjs/bitcoinjs-lib/pull/831 ?

**Comment by junderw** [comment]
Yes. Although we might want to copy the branch to local and open a new pull request with push credentials locked down.

**Comment by dcousens** [comment]
@lacksfish can you please re-open this PR to merge to `afk11:opt-in-bitcoincash-sighash`?

Or @junderw could make a local branch with `afk11:opt-in-bitcoincash-sighash` and then @lacksfish could PR to that instead?

**Comment by lacksfish** [comment]
Done so in #933, closing this for now.

**Pull request closed without merging**
