### PR TITLE
pre-2.0.0, deprecations

### PR DESCRIPTION
**Pull request by dcousens**
Most of this has been previously vetted, but this is the [almost] all inclusive 2.0.0 PR.

@weilu did we want to split it up into smaller PR's for simpler review over the next few days?

### CODE REVIEW

**Comment by dcousens** [comment]
Rebased on https://github.com/bitcoinjs/bitcoinjs-lib/pull/329

**Comment by dcousens** [comment]
Rebased on master.

**Comment by dcousens** [comment]
I've rebased on master.

This should be good to merge quite quickly, as it is almost all just removals, with the addition of `bufferutils.equal` and the movement of parameter type coercion to `TransactionBuilder` specifically.

Removed `ECPair` (will put it in another PR for review).

**Comment by dcousens** [comment]
Will merge before end of tonight, post reviews welcome, but most of this has already been reviewed several times, so it should just be a final check over.

**Comment by weilu** [comment]
I'll review this again today.

**Comment by dcousens** [comment]
Sounds good.  Will freeze as of now.

**Comment by dcousens** [comment]
Sounds good.  Will freeze as of now.

**Comment by dcousens** [comment]
Change log as of this PR.

---

Backward incompatible changes:

__removed__
- `bitcoin.crypto.HmacSHA256 ` // use `require('crypto').createHmac` instead
- `bitcoin.crypto.HmacSHA512 ` // use `require('crypto').createHmac` instead
- `bitcoin.base58check` // use `require("bs58check")` instead
- `bitcoin.Wallet` // build your own
- `bitcoin.HDNode.fromBuffer` // use `bitcoin.HDNode.fromBase58 instead
- `bitcoin.HDNode.fromHex` // use `bitcoin.HDNode.fromBase58 instead
- `bitcoin.HDNode.toBuffer` // use `bitcoin.HDNode.toBase58 instead
- `bitcoin.HDNode.toHex` // use `bitcoin.HDNode.toBase58 instead
- `bitcoin.Transaction.prototype.sign` // use `bitcoin.TransactionBuilder.prototype.sign` instead
- `bitcoin.Transaction.prototype.signInput` // use `bitcoin.TransactionBuilder.prototype.sign` instead
- `bitcoin.Transaction.prototype.validateInput` // use `hashForSignature` and ecdsa `verify`

__updated__
- `bitcoin.Message` -> `bitcoin.message`
- `bitcoin.Transaction` -> `bitcoin.RawTransaction`
- `bitcoin.TransactionBuilder` -> `bitcoin.Transaction`
- `bitcoin.HDNode.toBase58(isPrivate)` -> `bitcoin.HDNode.prototype.neutered().toBase58()` for exporting a extended public key and `bitcoin.HDNode.prototype.toBase58()` for exporting an extended private key
- `bitcoin.scripts.dataOutput ` -> `bitcoin.nullDataOutput`
- `Transaction.prototype.hashForSignature(prevOutScript, inIndex, hashType)` -> `Transaction.prototype.hashForSignature(inIndex, prevOutScript, hashType)` 

- `Transaction.prototype.addInput(hash, ...)`: `hash` could be a string, Transaction or Buffer -> `hash` can **now** only be a `Buffer`. 

- `TransactionBuilder.prototype.addInput(prevTx, ...)`, `prevTx` can still be a string, `Transaction` or `Buffer`.

- `Transaction.prototype.addOutput(scriptPubKey, ...)`: `scriptPubKey ` could be a string, `Address` or `Buffer` -> `scriptPubKey` can **now** only be a `Buffer`. 

- `TransactionBuilder.prototype.addOutput(scriptPubKey, ...)`, `scriptPubKey` can be a `string`, `Address` or `Buffer`.

**Comment by weilu** [comment]
LGTM

> TransactionBuilder API unchanged.

If it's not changed, it should not be under __updated__ section

**Comment by dcousens** [comment]
It was an amendment to what you had,  which specified changes,  even though
it was unchanged.

**Pull request merged**
