### PR TITLE
integration: avoid excessive blockchain requests

### PR DESCRIPTION
**Pull request by dcousens**
This should fix the related integration test occasionally failing due to a timeout.
Currently 900+ transactions are returned unnecessarily.

### CODE REVIEW

**Comment by dcousens** [comment]
@weilu post ACK if necessary

**Comment by weilu** [comment]
nice.

**Comment by dcousens** [comment]
Technically this is less malleability resistant, but I don't think that is
a major concern compared for this test case.

**Comment by weilu** [comment]
Malleability isn't what the tests here care about, so I think it's totally fine.

**Pull request merged**
