### PR TITLE
zcash compatibility

### PR DESCRIPTION
**Pull request by j4ys0n**
mainly this allows specifying byte length of versions & addresses, and adds the ability to specify version as a hex string instead of a number. i tried to keep the changes to a minimum.

### CODE REVIEW

**Comment by junderw** [comment]
Unfortunately, maintaining specialized code for altcoin support has historically been rejected, and I would have to agree.

It is recommended that you fork the project and maintain your set of patches for your community.

Let me know if you need any help figuring out how to do that.

Thanks.

**Comment by j4ys0n** [comment]
This is just an attempt to make the library more flexible. I maintain data operations for bitcoin and a lot of alt coin networks at a data service provider and have one central data processing application. 

Encouraging maintenance of separate repos seems very non-inclusive and contributes to keeping communities separate. I'd be happy to add typescript support also. I maintain tools and libraries for many chains.

**Comment by junderw** [comment]
> Encouraging maintenance of separate repos seems very non-inclusive and contributes to keeping communities separate.

Open source has been like this for ages: non-compatible feature sets are managed via forks.

This way bitcoin devs can make cool stuff, zcash devs can then merge those cool things to zcash if they want or reject it if they want. Similarly bitcoin can merge things from zcash.

It's very inclusive.

What you are asking is the beginning of a slippery slope that ends with one repository supporting everything, and once the zcash specific people abandon the project, dead un-maintained code is prone to breakage.

We wouldn't expect Bitcoin Core to maintain zcash code (hey, downloading one binary called "bitcoind" that you can switch to any alt by doing "bitcoind --zcash" is very convenient...)

We maintain the inclusivity via the open source licenses we use.

You are more than welcome to fork us, and more than welcome to continue to merge our code into your fork. We have nothing against zcash, it's just a maintainability issue.

Also, off-topic, there's a WIP typescript re-write for this library I'm working on currently if you'd like to take a gander.

https://github.com/bitcoinjs/bitcoinjs-lib/pull/1319

Cheers

**Comment by j4ys0n** [comment]
Not trying to start an argument but this isn't bitcoin core and I'm not advocating for adding zcash support to bitcoin. And for the record, Parity makes wallets for bitcoin, zcash and ethereum, and the ethereum wallet can sync many different chains by just changing the `chain` flag.

I didn't really add that much, just the ability to be able to specify a 2 byte address version and the ability to specify that version as a hex string so that one could do: `address.toBase58Check(addres_buffer, '1cbd');`

Would you be open to adding this PR as a branch?

I thought about adding native xpub support also (to reduce dependencies). I already have an xpub TypeScript implementation. I'd also be willing to contribute more and help maintain moving forward.

**Comment by junderw** [comment]
Unless you have any plans of deleting your github, a simple search for zcash in our repo will lead anyone to this PR, and subsequently your branch. So copying the branch doesn't really do much to help anyone.

As for native BIP32 support, BIP32 was separated into a separate repository primarily because many non-bitcoin projects use BIP32, so including it in bitcoinjs-lib means that altcoins have to package all this useless bitcoin stuff in their apps.

We are considering moving to a mono-repo style for git management, but as far as npm packaging is concerned, BIP32 should remain separate.

**Pull request closed without merging**
