### PR TITLE
Switch from create-hash, ripemd160 to noble-hashes

### PR DESCRIPTION
**Pull request by paulmillr**
`hash160`, `hash256` methods were adjusted because it's more performant to not do Buffer.from twice. I suppose some future update of bitcoinjs will remove buffer altogether.

create-hash and ripemd160 were **not** removed from dependency tree. Reasons:

- bip32: needs a new release
- bip39, bs58check: need switch to hashes

### CODE REVIEW

**Comment by junderw** [comment]
Maybe we should do bip39 and bs58check first, then cut releases for those and then do this.

**Comment by paulmillr** [comment]
https://github.com/bitcoinjs/bip39/pull/188, https://github.com/bitcoinjs/bs58check/pull/41

**Comment by paulmillr** [comment]
What do you think regarding merging those?

**Comment by junderw** [comment]
Would you mind converting the travis yml to a Github CI yml so that it can run the tests on the PR?

Thanks.

**Comment by paulmillr** [comment]
Done. Copy-pasted your ci config from the repository and adjusted a bit. All tests are passing.

**Comment by junderw** [comment]
I have merged and published everything.

Please remove create-hash :tada:

**Comment by junderw** [comment]
> I suppose some future update of bitcoinjs will remove buffer altogether.

Maybe ChatGPT can help with this. lol

**Comment by paulmillr** [comment]
That did not help. wif still depends on old stuff.

https://github.com/bitcoinjs/wif/pull/30

regtest-client also does, but it's devDependency - probably not worth to upgrade; users won't see create-hash after bitcoinjs upgrade already.

**Comment by junderw** [comment]
Is wif even used outside tests?

**Comment by paulmillr** [comment]
Not used anywhere, actually. Removed, all good now. create-hash became devDependency.

**Comment by paulmillr** [comment]
Seems good to go!

**Comment by paulmillr** [comment]
@junderw ping

**Review by junderw — APPROVED** [review]

**Pull request merged**
