### PR TITLE
rm Templates exports

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by dcousens** [comment]
We could remove the `bitcoin.address` exports to no ill effect too

**Comment by dcousens** [comment]
The useful functions there are `toOutputScript` and `fromOutputScript`,  both of which are useful for their classification properties.

Maybe they should go under the `classify` internal export for now until we figure out the best thing to do there?

Ultimately this refactor has cleaned it into two ideas.
* Encoding/decoding of scripts, addresses, inputs, signatures, etc
* Classification of scripts (unsafe)

**Comment by dcousens** [comment]
I haven't removed the `.address` export in this PR however,  but,  if I'd __really__ like some discussion around this if anyone is able.

**Comment by dcousens** [comment]
This PR is reliant on https://github.com/bitcoinjs/bitcoinjs-lib/pull/1120,  please review/merge that,  then I can fix the tests for this and merge if necessary

**Comment by jprichardson** [comment]
> We could remove the bitcoin.address exports to no ill effect too

Different PR IMHO. I don't like large PRs - you don't either (https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/CONTRIBUTING.md#workflow) 😛I guess the title of the PR could be changed?

**Comment by dcousens** [comment]
@jprichardson this PR is only focused on `rm Templates exports` AFAIK.
The only other changes it enforces is in https://github.com/bitcoinjs/bitcoinjs-lib/pull/1119/commits/0d0f1d0847eebedab55f0dc7d3bc51b3100d86aa,  which is required for this change to prevent a circular dependency.

**Comment by dcousens** [comment]
Fixing integration tests,  then should be `ready to merge`

**Comment by junderw** [comment]
LGTM so far. Only two places still use templates in integration tests...

I'll wait for the fix to ACK

**Comment by dcousens** [comment]
@junderw please see now, integratoin tests passing locally

**Comment by dcousens** [comment]
Ping @junderw?

**Comment by gbenattar** [comment]
The https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bitcoinjs-lib/index.d.ts is no longer accurate - payment is missing which forces the use of the type any() in TypeScript projects.

**Comment by dabura667** [comment]
@gbenattar we do not maintain that... someone else made it without our knowledge.

**Comment by gbenattar** [comment]
Understood. It is a great addition btw, do you think we could include and maintain it? I will be happy to help.

**Comment by dcousens** [comment]
@gbenattar please see the [README](https://github.com/bitcoinjs/bitcoinjs-lib#typescript-or-vscode-users).

> WARNING: These Typescript definitions are not maintained by the maintainers of this repository, and are instead maintained at DefinitelyTyped. Please report any issues or problems there.

**Pull request merged**
