### PR TITLE
Psbt: fix an issue in signInputAsync

### PR DESCRIPTION
**Pull request by pluswave**
psbt: fix an issue for error process in signInputAsync.
    
    If keyPair.sign returns a promise and async rejects,
    (i.e, user press reject on hardware wallet)
    catch and reject the wrapper promise now.

### CODE REVIEW

**Comment by junderw** [comment]
run `npm run format` to fix format

then `npm run lint` and `npm run lint:tests` and fix any errors.

**Comment by junderw** [comment]
Also, please elaborate on the problem.

**Comment by junderw** [comment]
Please enable us to push to your branch.

Here is a fix:

```diff
diff --git a/src/psbt.js b/src/psbt.js
index f6daae6d..ad76d033 100644
--- a/src/psbt.js
+++ b/src/psbt.js
@@ -490,7 +490,8 @@ class Psbt {
   ) {
     if (!keyPair || !keyPair.publicKey)
       return Promise.reject(new Error('Need Signer to sign input'));
-    let r, hashAndType;
+    let r;
+    let hashAndType;
     try {
       hashAndType = getHashAndSighashType(
         this.data.inputs,
diff --git a/test/psbt.spec.ts b/test/psbt.spec.ts
index 74011ed9..da35dbf9 100644
--- a/test/psbt.spec.ts
+++ b/test/psbt.spec.ts
@@ -1,7 +1,14 @@
 import * as assert from 'assert';
 import { describe, it } from 'mocha';
 
-import { bip32, ECPair, networks as NETWORKS, Psbt, Signer, SignerAsync } from '..';
+import {
+  bip32,
+  ECPair,
+  networks as NETWORKS,
+  Psbt,
+  Signer,
+  SignerAsync,
+} from '..';
 
 import * as preFixtures from './fixtures/psbt.json';
 
@@ -23,37 +30,39 @@ const upperCaseFirstLetter = (str: string): string =>
   str.replace(/^./, s => s.toUpperCase());
 
 const toAsyncSigner = (signer: Signer): SignerAsync => {
-  let ret:SignerAsync = {
+  const ret: SignerAsync = {
     publicKey: signer.publicKey,
-    sign: (hash:Buffer, lowerR: boolean | undefined) =>{
-      return new Promise((resolve,rejects)=>{
-        setTimeout(()=>{
-          try{
-            let r = signer.sign(hash, lowerR);
-            resolve(r);
-          }
-          catch(e){
-            rejects(e);
-          }
-        },10);
-      });
-    }
+    sign: (hash: Buffer, lowerR: boolean | undefined): Promise<Buffer> => {
+      return new Promise(
+        (resolve, rejects): void => {
+          setTimeout(() => {
+            try {
+              const r = signer.sign(hash, lowerR);
+              resolve(r);
+            } catch (e) {
+              rejects(e);
+            }
+          }, 10);
+        },
+      );
+    },
   };
   return ret;
 };
-const failedAsyncSigner = (publicKey:Buffer) => {
+const failedAsyncSigner = (publicKey: Buffer): SignerAsync => {
   return {
     publicKey,
-    sign: (_:Buffer, lowerR: boolean | undefined):Promise<Buffer> =>{
-      console.log(lowerR);
-      return new Promise( (_,reject)=>{
-        setTimeout( ()=>{
-          reject(new Error("sign failed"));
-        },10);
-      });
-    }
-  }
-}
+    sign: (__: Buffer): Promise<Buffer> => {
+      return new Promise(
+        (_, reject): void => {
+          setTimeout(() => {
+            reject(new Error('sign failed'));
+          }, 10);
+        },
+      );
+    },
+  };
+};
 // const b = (hex: string) => Buffer.from(hex, 'hex');
 
 describe(`Psbt`, () => {
@@ -203,13 +212,13 @@ describe(`Psbt`, () => {
               f.shouldSign.sighashTypes || undefined,
             );
           });
-          await assert.rejects( async() =>{
+          await assert.rejects(async () => {
             await psbtThatShouldsign.signInputAsync(
               f.shouldSign.inputToCheck,
               failedAsyncSigner(ECPair.fromWIF(f.shouldSign.WIF).publicKey),
               f.shouldSign.sighashTypes || undefined,
             );
-          },/sign failed/ );
+          }, /sign failed/);
         }
 
         if (f.shouldThrow) {
diff --git a/ts_src/psbt.ts b/ts_src/psbt.ts
index 266b7c11..23e3c1b8 100644
--- a/ts_src/psbt.ts
+++ b/ts_src/psbt.ts
@@ -583,7 +583,8 @@ export class Psbt {
     if (!keyPair || !keyPair.publicKey)
       return Promise.reject(new Error('Need Signer to sign input'));
 
-    let r: Buffer | Promise<Buffer>, hashAndType: { hash: Buffer, sighashType: number };
+    let r: Buffer | Promise<Buffer>;
+    let hashAndType: { hash: Buffer; sighashType: number };
     try {
       hashAndType = getHashAndSighashType(
         this.data.inputs,
@@ -593,15 +594,17 @@ export class Psbt {
         sighashTypes,
       );
       r = keyPair.sign(hashAndType.hash);
-    }
-    catch (e) {
+    } catch (e) {
       return Promise.reject(e);
     }
     return Promise.resolve(r).then(signature => {
       const partialSig = [
         {
           pubkey: keyPair.publicKey,
-          signature: bscript.signature.encode(signature, hashAndType.sighashType),
+          signature: bscript.signature.encode(
+            signature,
+            hashAndType.sighashType,
+          ),
         },
       ];
 
```

**Comment by pluswave** [comment]
How to do that ?
> Please enable us to push to your branch.

**Comment by junderw** [comment]
Enter the checkbox on the bottom of the right column of this pull request.

It will allow us to push to your Pull Request branch only (can not push to any other of your branches)

範囲を選択_001

**Comment by junderw** [comment]
closing in favor of #1582 

Please review #1582

**Comment by junderw** [comment]
Published in v5.1.10

**Pull request closed without merging**
