### PR TITLE
Add payments.p2data

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by dcousens** [comment]
Alternatives as discussed in https://github.com/bitcoinjs/bitcoinjs-lib/issues/1115

- [ ] `payments.p2data`
- [ ] `payments.data`
- [ ] `payments.embed`
- [ ] `payments.nullData`
- [ ] `payments.nulldata`
- [ ] `payments.p2nd`

**Comment by junderw** [comment]
LGTM

**Comment by junderw** [comment]
payments.embed

**Comment by dcousens** [comment]
@fanatid @afk11  any preference?

**Comment by jprichardson** [comment]
LGTM. `payments.embed` or `payments.p2data` are good.

**Comment by dcousens** [comment]
Rebased on https://github.com/bitcoinjs/bitcoinjs-lib/pull/1127

**Pull request merged**
