### PR TITLE
New function: script.solveOutput

### PR DESCRIPTION
**Pull request by afk11**
Replaces https://github.com/bitcoinjs/bitcoinjs-lib/pull/697 because that targeted another base.

### CODE REVIEW

**Comment by afk11** [comment]
This tests both sighash implementations against live vectors, plus the test logic may well end up incorporated into signing somewhere

**Comment by afk11** [comment]
Rebased

**Comment by afk11** [comment]
Rebased, time for merge?

**Comment by afk11** [comment]
One of the motivations of this PR is to make stuff like this easier: 
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L150

We could run solveOutput, save that as prevOutput, then we get the following without having to duplicate work:
```
 {
    type: outputType,
    script: scriptCode,
    solvedBy: solvedBy,
    requiredSigs: requiredSigs
}
```

**Comment by dcousens** [comment]
@afk11 we could maybe make it private for now,  try out the use cases then decide?

**Comment by afk11** [comment]
I still think we need this, mind merging it?

**Comment by dcousens** [comment]
ACK,  but I don't think the name is right as it implies `solveOutput(ouput) -> solvedOutput` ... aka, it is a verb.
It is actually akin `whatSolvesThisOutput(output)`

**Comment by dcousens** [comment]
@afk11 thoughts on this?
It is useful,  but,  I struggled with the exact use-case... maybe an integration test?

**Pull request closed without merging**
