### PR TITLE
Adding getPubKeyHash to HDNode and keypair

### PR DESCRIPTION
**Pull request by runn1ng**
I found out this can get quite useful.

If you think this is good to have, I will add some tests.

### CODE REVIEW

**Comment by dcousens** [comment]
I could never decide if this was worth it.   @fanatid @jprichardson ?
I'm neutral either way.

**Comment by runn1ng** [comment]
I will work on the tests if it's worth the time spent on them :)

I would definitely use it; although I am actually using it from HDNode, so `node.getIdentifier` is enough anyway - but it's less clear what it actually does.

**Comment by dcousens** [comment]
Needs rebase

**Comment by runn1ng** [comment]
Rebased + added some tests. Again I don't really care that much if it won't be accepted, I can use it by `getIdentifier`

**Comment by dcousens** [comment]
@fanatid penny for your thoughts?

**Comment by fanatid** [comment]
@dcousens idk, at least if you want merge this, I recommend rename `getPubKeyHash` to `getPublicKeyHash`
@runn1ng OOI for what purpose you want use `getPubKeyHash` from `HDNode`?

**Comment by dcousens** [comment]
IMHO I almost always just do `bitcoin.crypto.hash160(keyPair.getPublicKey())`

**Comment by runn1ng** [comment]
@fanatid 
Well, I wanted to use it (in Trezor client) to check if transaction with output to my own node has correct script. Trezor tells me the final outputs and I want to check if it created the script correctly; when Trezor creates the output to its own node (most often change node), I send it only the path of the node, not Base58check address (then the user doesn't need to confirm on device; it's his own address!). To check if the script is correct, I derive the HDNode on the client and compare the script in the transaction with the expected script, for which I need the pubkeyhash.

Sure, I can first derive a b58c address and then decode it and get the hash from there, but that's one extra step. :)

**Comment by dcousens** [comment]
Needs rebase.

I'm going to ACK this change,  as it would probably be useful for many.
Anyone against?

**Comment by jprichardson** [comment]
> Anyone against?

Nope. I'm not keen on the naming scheme... but no need for me to bikeshed on 2.x. We can save that fun for 3.x =)

**Comment by dcousens** [comment]
@runn1ng if you rebase I'll merge.

**Comment by dcousens** [comment]
ping @runn1ng

**Comment by dcousens** [comment]
ping @runn1ng

**Comment by runn1ng** [comment]
Going to rebase now, sorry about the huge delay

**Comment by runn1ng** [comment]
Hm. The integration tests are failing, I am not sure why.

**Comment by dcousens** [comment]
@runn1ng the integration tests failing are due to Blocktrail failing to give us an unspent to test with (ping @rubensayshi).
Not your fault.

**Comment by dcousens** [comment]
Still not sure how I feel. 
`pubKeyHash` is only going to become less useful now that SegWit is soon upon us.
It's almost identical,  but without the fee subsidy.

**Comment by jprichardson** [comment]
> pubKeyHash is only going to become less useful now that SegWit is soon upon us.
P2WSH w/ a 160-bit hash will be identical in security, and will have a fee subsidy.

👍

**Pull request closed without merging**
