### PR TITLE
Merge daburra667's forks331 into master

### PR DESCRIPTION
**Pull request by Melvillian**
I pulled the https://github.com/dabura667/bitcoinjs-lib/tree/forks331/ branch in locally and merged it with `master`. I was thinking we just use the `forks331` as our main codebase and publish that, but BitGo devs have made commits to the master branch in the past so we want to preserve those.

If there are future hardforks that require additional bitcoinjs-lib signing logic, we can either write them ourselves and merge them into our `master` branch, or if someone like dabura667 writes the logic for us we can update our local `forks331` branch from upstream and merge that into `master`.

### CODE REVIEW

**Comment by Melvillian** [comment]
This PR was intended for https://github.com/bitgo/bitcoinjs-lib/, I'm closing here.

**Comment by dcousens** [comment]
@Melvillian out of interest,  as we see this happen to poor bitcoin/bitcoin __all__ the time,  what happened here?

**Comment by Melvillian** [comment]
@dcousens plain old user error. I had 3 tabs open, one for bitcoinjs/bitcoinjs-lib, one for BitGo/bitcoinjs-lib, and one for Melvillian/bitcoinjs-lib, and I accidentally went to github.com/bitcoinjs/bitcoinjs-lib to create the PR rather than github.com/BitGo/bitcoinjs-lib.

The strange thing was that while I'm pretty confident I ran `git push --set-upstream origin merge-forks331-into-master` where origin was BitGo/bitcoinjs-lib, when I accidentally when to bitcoinjs/bitcoinjs-lib they yellowed text box that prompts you to create a new PR request popped up. I would have thought that would only come up for the repo the remote was actually pushed to (BitGo/bitcoinjs-lib) but Github's trying to be smart I guess.

**Comment by dcousens** [comment]
Cheers for explanation! :)

**Comment by junderw** [comment]
git can be hard sometimes.

Glad to be of help.

**Comment by junderw** [comment]
I also think github's pull request UI makes some weird assumptions for the default master branch to PR to...

**Comment by dcousens** [comment]
@junderw lies! Upstream is king!

**Comment by junderw** [comment]
Except for altcoin forks... Electrum has at least 5 PRs every month meant for Electrum-DASH or some such.

**Pull request closed without merging**
