### PR TITLE
rm bitcoin.script circular dependencies with templates

### PR DESCRIPTION
**Pull request by dcousens**
Resolves https://github.com/bitcoinjs/bitcoinjs-lib/issues/905 (hopefully)

@maxcloudwgh please test

### CODE REVIEW

**Comment by maxcloudwgh** [comment]
Ok,updates is take effect, but new error occurs @dcousens 

image

**Comment by dcousens** [comment]
@maxcloudwgh can you provide the call stack for that error?

**Comment by maxcloudwgh** [comment]
@dcousens ,sorry, how to do that

**Comment by maxcloudwgh** [comment]
image

**Comment by maxcloudwgh** [comment]
image

**Comment by maxcloudwgh** [comment]
it seems that input is not required properly

**Comment by dcousens** [comment]
@maxcloudwgh thanks!
I added c390943,  see how you go now

**Comment by dcousens** [comment]
Squashed,  ready for review @afk11 @junderw then merge + release

**Pull request merged**
