### PR TITLE
[WIP] Integrated TS types + type tests

### PR DESCRIPTION
**Pull request by torkelrogstad**
Work in progress, not ready for merge. 

I'm opening this PR to get some feedback if this is a nice way to do the TS definitions. I took the types from DefinitelyTyped, and tweaked them a bit. The type checking tests only checks for return types. Is this sufficient, or should parameters be tested as well? Would be a lot of work...

### CODE REVIEW

**Comment by torkelrogstad** [comment]
Will add copyright notices.

Question regarding the `opcodes` part of the default export from `index.js`. I see it is taken from another package, `bitcoin-ops`. Would it make more sense to not add TS typings for those codes? Seeing as they're not part of `bitcoinjs-lib` themselves. FWIW, they're currencly part of the `@types/bitcoinjs-lib` typings

**Comment by dcousens** [comment]
I think maybe DefinitelyTyped might still be the better place seeing as we have many modules.

**Comment by torkelrogstad** [comment]
I see that there's several small packages available for different BIPs and such. At least adding for `bitcoin-ops` would be trivial, and something I would gladly do. Would that be of interest?

**Comment by torkelrogstad** [comment]
Added credit to original author. Not sure if format is correct. 
Added tests and types for `crypto` and `author`.

@dcousens

**Comment by torkelrogstad** [comment]
Regardin the `bitcoin-ops` question, it turns out writing TS definitions isn't necessary, as TS allows for JSON to be imported with type information. I've made a PR with an updated README: https://github.com/bitcoinjs/bitcoin-ops/pull/3

**Comment by junderw** [comment]
@torkelrogstad Good news: I am converting bitcoinjs-lib into a TypeScript library currently.

I am going to start working on TypeScript-ifying some of the bitcoinjs-lib dependencies as well, and then start adding type aliases to differentiate.

If you would like to help me out, make a pull request against my repo:

https://github.com/junderw/bitcoinjs-lib/tree/typeScript

Once I get it semi-presentable, I will make a pull request to the main repo for review. It's kind of a mess right now, and I just kind of left the tests as-is.

**Comment by junderw** [comment]
https://github.com/junderw/bitcoinjs-lib/pull/3/files?utf8=%E2%9C%93&diff=unified&w=1

I made a PR on my fork that is from the TS branch to a branch where I just renamed the js files to ts. It improved the diff some.

**Comment by junderw** [comment]
closed in favor of #1319

**Pull request closed without merging**
