### PR TITLE
package: remove uglify-js

### PR DESCRIPTION
**Pull request by dcousens**
It is not our responsibility to uglify the code.

If they want to uglify it, there are plenty of tools to which they could use, just like the rest of their build process.

@weilu thoughts?

### CODE REVIEW

**Comment by dcousens** [comment]
@weilu still happy to hear feedback, but I can't foresee any real issue with this.

**Comment by weilu** [comment]
Here's a reason why this change is a bad idea:

```
±  |master ✗| → ll -h bitcoin.js 
-rw-r--r--@ 1 wlu  401060983   620K Feb 16 19:47 bitcoin.js

±  |master ✗| → ll -h bitcoinjs-min.js 
-rw-r--r--@ 1 wlu  401060983   149K Oct  7 15:34 bitcoinjs-min.js
```

**Comment by weilu** [comment]
After I posted it I realized that the minified bitcoinjs was of a much older version. Current master yields:

```
±  |master ✗| → ll -h bitcoinjs-min.js 
-rw-r--r--@ 1 wlu  401060983   424K Feb 16 19:52 bitcoinjs-min.js
```

@dcousens I'm curious to what makes bitcoinjs-lib 3x more bloated than 4 months ago

**Comment by dcousens** [comment]
Crypto-browserify has grown substantially in size.  That may accommodate
for some of it.

**Pull request merged**
