### PR TITLE
Bitcoin Cash (and Gold) TX redemption

### PR DESCRIPTION
**Pull request by dcousens**
In-repository branch for https://github.com/bitcoinjs/bitcoinjs-lib/pull/831

### CODE REVIEW

**Comment by dcousens** [comment]
@Melvillian please report if this is what you needed, or otherwise let others know what might need to be added to make it feasible.

**Comment by dcousens** [comment]
Thanks @junderw for rebase

**Comment by junderw** [comment]
Going to stop rebasing in case someone is referencing the hashes, plus a single merge commit is easier to review rather than reviewing the whole sighash commits every time.

Also, @dcousens what do you think about tagging this branch as `vX.X.X-forks` moving forward?

**Comment by afk11** [comment]
The bitcoin cash address change is coming up soon. Unfortunately they made so many changes that the bech32 code cannot be parameterized to make it work. 

https://github.com/btccom/bech32/pull/1

There are changes beside just cash addresses in this branch, but it should be a start if someone wanted to include it in the bitcoinjsforks package.

**Comment by dakk** [comment]
Not sure if this is the right place, but is it possible to have an example of using bitcoincash library to send funds from a 2-of-3 multisig address? I'm getting "16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26" but I don't understand if I'm using it right.

I think the problem could be the "spk" in the inputs; what should I use in a multisig wallet?

**Comment by dabura667** [comment]
@dakk iirc spk should be the redeemscript for multisig p2sh.

Make sure you pass the input amounts when signing though.

**Comment by dakk** [comment]
@dabura667 using the reedemScript as spk I'm able to push the transaction via bitpay apis (https://bch-insight.bitpay.com/tx/1215665c08cd6e95b0c481b65e23ff4e815d6dc3032feff8de4d79efeec3a427) but the transaction result invalid when I try to push it in another explorers.

The transaction hex is: 
```0200000001267135f005a438e2ba873184775223dd3adf6e2a3faddd8bc2d37d82a8b71af800000000d900473044022008e400fc59e32ce4a7f1ab4668082ca52ee1da1a20e569b30748f515534add9d02202d6d814d98c6b585d63b7b6552c0f657dd50e0cbd65ade23438d24bcc5d7a5ca414730440220601c754cb599b45aea2f2c83bcf73f1b4def4c22b58951148206ea10fb89acce022022e0cdcef0cc46bca7d3521c5fe6d66b3b28550639c0a6a817c380c6f257dbf141473044022006727645fa97b7945926d9c89021c17db930c496a1220a9e17dc21055294947a02204d41de6c4fbc8a6b1827f9dcb5e6907efa41ef3afaeeac7fad6b02fc5d5825f441ffffffff0159b50f00000000001976a9146cb6204af28ae60565552e8d521b7f243fe3f77888ac00000000```

And when I try to broadcast I get the error: "An error occured:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26"

This is my piece of code (which already works using bitcoinjs with Bitcoin):

```javascript
		var pubkeys_raw = $scope.npo.pubkeys.map(function (hex /*: string*/) { return new buffer.Buffer (hex, 'hex'); });
			
		var redeemScript = bitcoin.script.multisig.output.encode (parseInt ($scope.npo.n), pubkeys_raw);
		var scriptPubKey = bitcoin.script.scriptHash.output.encode (bitcoin.crypto.hash160 (redeemScript));
		var address = bitcoin.address.fromOutputScript (scriptPubKey, bnetwork);

		console.log (address);

		/* Get unspent */
		$http.get ('https://api.blocktrail.com/v1/BCC/address/' + address + '/unspent-outputs?api_key=136d6fb4f662c7d177812bd7a8ab3d0918f22d13').success (function (data) {
			var txs = data.data;
			var txb = new bitcoin.TransactionBuilder (bnetwork);
			var cumulative = 0.0;
			var fee = $scope.calculateFee (txs.length);

			for (var i = 0; i < txs.length; i++) {
				cumulative += parseInt (txs[i].value);
				console.log ('value input', txs[i].value)
				txb.addInput (txs[i].hash, txs[i].index, bitcoin.Transaction.DEFAULT_SEQUENCE, redeemScript);
			}

			if (cumulative == 0 || cumulative - fee < 0) {
				return;
			}

			txb.addOutput($scope.npo.address, cumulative - fee);
			

			txb.enableBitcoinCash(true);
			txb.setVersion(2);

			var hashType = bitcoin.Transaction.SIGHASH_ALL | bitcoin.Transaction.SIGHASH_BITCOINCASHBIP143;

			/* Add signatures */
			for (var j = 0; j < txb.tx.ins.length; j++) {
				for (var z = 0; z < parseInt ($scope.npo.n); z++) {
					txb.sign (j, $scope.npo.backup[z].pair, null, hashType, txs[j].value);
					console.log ('value sign', txs[j].value)
				}
			}


			/*var tx = txb.build ();
			var txhex = tx.toHex ();*/

			var txb2 = bitcoin.TransactionBuilder.fromTransaction (txb.build (), bnetwork, bitcoin.Transaction.FORKID_BCH);

			var tx = txb2.build ();
			var txhex = tx.toHex ();
			console.log (txhex);

			/* Broadcast */
			$http.post ('https://bch-insight.bitpay.com/api/tx/send', {rawtx: txhex}).success (function (data) {
			}).error (function (data) {
			});
		});
    };

```

**Comment by dabura667** [comment]
`txb.sign (j, $scope.npo.backup[z].pair, null, hashType, txs[j].value);`

should be

`txb.sign (j, $scope.npo.backup[z].pair, redeemScript, hashType, txs[j].value);`

**Comment by dabura667** [comment]
also, lol @ bitpay's BCH insight... did they just decide not to verify... your transaction has no redeemscript and is invalid, yet they show it...

Now we know not to use insight... wow...

**Comment by dakk** [comment]
@dabura667 lol, I won't use it anymore then. Putting reedemScript in the sign call, I'm getting the error: "PrevOutScript must be P2SH"

**Comment by dabura667** [comment]
change `txb.addInput (txs[i].hash, txs[i].index, bitcoin.Transaction.DEFAULT_SEQUENCE, redeemScript);`

to `txb.addInput (txs[i].hash, txs[i].index, bitcoin.Transaction.DEFAULT_SEQUENCE, scriptPubKey);`

**Comment by dakk** [comment]
It works! Thank you @dabura667 , I finally understood what I was missing.

**Comment by ptronico** [comment]
Hi guys! I appreciate if anyone can help me!

We are creating a 2-of-3 multisig Bitcoin Cash transaction on backend and passing the transaction hex (`txHex`) and redeem script (`redeemScriptHex`) to be able to do one sign on frontend. So, on backed we are running `bitcoin-core` and `bitcoin-unlimited` and on frontend we were using the latest released of `bitcoinjs-lib` and now, it's `opt-in-bitcoincash-sighash` branch. The workflow for BTC transactions is working well, but not for BCH transactions. Basically we are doing this:

```javascript
tx = bitcoin.Transaction.fromHex(txHex); 
redeemScript = bitcoin.script.decompile(bitcoin.script.fromASM(redeemScriptHex))[0];

// For BTC
txb = bitcoin.TransactionBuilder.fromTransaction(tx, bitcoin.networks.testnet);
txb.sign(i, keyPair, redeemScript);

// For BCH
hashTyped = bitcoin.Transaction.SIGHASH_ALL | bitcoin.Transaction.SIGHASH_BITCOINCASHBIP143;
txb = bitcoin.TransactionBuilder.fromTransaction(tx, bitcoin.networks.testnet, bitcoin.Transaction.FORKID_BCH);
txb.sign(i, keyPair, redeemScript, hashTyped, value);
```

The transaction is signed without raising errors, but on backend we get uncompleted signed transaction with this message:
> Signature must be zero for failed CHECK(MULTI)SIG operation

Thanks a lot!

**Comment by dabura667** [comment]
Try signing it in the opposite order. (Key a then key b... in stead do Key b then key a)

Tell me what happens.

**Comment by ptronico** [comment]
I got the same result... When I run `decoderawtransaction` on `bitcoin unlimited cash` I get `"version": 1`. Do you think the issue may be related with `version 2` transactions on `bitcoinjs-lib`? Thanks!

**Comment by dakk** [comment]
@junderw nope, my code works on bitcoincash with multisig and version 2

**Comment by pbca26** [comment]
not sure if this is a good place to ask but are you guys planning to add new Bitcoin Cash Address support any time soon?

**Comment by junderw** [comment]
> are you guys planning to add new Bitcoin Cash Address support any time soon?

Nope. This is a branch for signing transactions, adding the concept of forkID to TransactionBuilder so you can sign.

Adding address would require adding the concept of "Bitcoin Cash" to ECPair, HDNode, and Address objects.

Scope would be way to big and specialized towards bitcoin cash.

However, you can pull in your own library, there are plenty around the internet.

https://github.com/btccom/cashaddress-js

**Comment by dcousens** [comment]
Shall we close?

**Comment by afk11** [comment]
As good a time as any - the BCH peeps have bitcoincash-js, and at least we have some examples of how to do it!

**Pull request closed without merging**
