### PR TITLE
add from/toBech32

### PR DESCRIPTION
**Pull request by dcousens**
Reliant on https://github.com/bitcoinjs/bech32/pull/10

#### TODO
- [x] Add `toBech32`/`fromBech32`
- [ ] ~~Add `toString`/`fromString`~~
- [x] Add `toOutputScript` and `fromOutputScript` support

### CODE REVIEW

**Comment by runn1ng** [comment]
In the fixtures, what is the difference between bech32/invalid and invalid/frombech32? Why do these differ slightly?

Other than that, looks fine to me

**Comment by dcousens** [comment]
Will add `toOutputScript`/`fromOutputScript` support soon.

`toString`/`fromString` would be unnecessary and have a non-sensible return type.

**Comment by kabutosamourai** [comment]
Is this work going to abstract the human-readable prefixes to `networks`, or will that be a future addition?

**Comment by dcousens** [comment]
@kabutosamourai yes.

I was thinking `network.bech32` or `network.bech32Prefix` - any preference?

**Comment by dcousens** [comment]
PR ready to merge,  ping reviewers

**Comment by dcousens** [comment]
@kabutosamourai I added you to the org :+1: - no pressure,  but your input is valuable :+1:

**Comment by kabutosamourai** [comment]
`network.bech32` makes sense.

The new internals of `fromOutputScript` and `toOutputScript` are really nice.

ACK

**Pull request merged**
