### PR TITLE
1.x

### PR DESCRIPTION
**Pull request by dcousens**
This PR encompasses a `1.5.x` release.

I've back-ported the fixes from master (which is progressing towards `2.0.0` and contains several breaking changes).

### CODE REVIEW

**Comment by rubensayshi** [comment]
hmm, I asume / hope you can also merge in https://github.com/bitcoinjs/bitcoinjs-lib/pull/373 for the `v1.5.1` release?

**Comment by dcousens** [comment]
@rubensayshi what is BC?

**Comment by rubensayshi** [comment]
@dcousens BC = Backward Compatibility  but Compatibility is such a shitty word to type :P

**Comment by weilu** [comment]
Looks good to me. @rubensayshi @dcousens there's always 1.5.2. I don't see the need of blocking a bug fixing release with additional bug fixes :)

**Comment by rubensayshi** [comment]
@weilu but I think that fix should be merged asap since I'm pretty amazed that nobody other than me is running into these issues with 2of3 signing.

**Comment by weilu** [comment]
How does releasing 1.5.1 without it slow down the merge? ;)

Cheers
Wei

**Comment by dcousens** [comment]
Will merge, looks like it needs a rebase.   Will hit `1.5.2` very soon thereafter.

**Comment by dcousens** [comment]
Just realised, this can't be merged of course, haha.

Released as `1.5.1`.

**Comment by rubensayshi** [comment]
can't be merged? why?

**Comment by dcousens** [comment]
@rubensayshi master is `2.0.0`, this PR wasn't actually a BR, more of a branch review to be honest.  
I'll back port  future fixes to it and review them here.  I'm not sure if there might be a better work flow though.  Perhaps a `1.5.x-release` branch.

**Comment by rubensayshi** [comment]
hmm, considering we're doing normal PRs against master and you're working towards a `2.0.0` it indeed makes more sence to back port stuff from `master` to `1.5.x` indeed

**Comment by dcousens** [comment]
Ran the following cherry-pick:

`git cherry-pick c52420a 29b93b8 000625c 745eace 3e44c41 4d08ae5 7cd60aa e80f480 69eb58c a29761c 4660b84 6c02e16`

The only conflicts were in `745eace` and `3e44c41` with some `require`.

**Comment by dcousens** [comment]
Published as `1.5.2`, but feel free to re-ACK any concerns here.

**Comment by dcousens** [comment]
`git cherry-pick 57856a0a258eab73b45355c008a2b0c8a28d1bd2 281ecdc06ee68cf602e0f8ea618ca2d63d3972b6 886d38ebee0ab4c5cf021efa70a6f6e42
34ff3de 0e0a12da279d501a7c2a10b0480ab664e52cea5c`

Picked off master, no conflicts.

Published as `1.5.3`.

**Comment by dcousens** [comment]
```
git cherry-pick 5fadfcc e939aa0 889ed9b
```

No conflicts.

Published as `1.5.4`

**Comment by dcousens** [comment]
Before `1.6.0` can be published, deprecation's must be added for `estimateFee` and the removed networks.

**Comment by dcousens** [comment]
```
git cherry-pick b5c4230 64e206c 689f444 b558747
```

Picked off master, no conflicts.

Published as 1.5.5.

**Comment by dcousens** [comment]
```
git cherry-pick b5c4230 64e206c 689f444 b558747
```

Picked off master, no conflicts.
Had to add https://github.com/bitcoinjs/bitcoinjs-lib/commit/07a25100469244806f4cc62cecb6eb570ab41d10 to pass the tests.

Published as 1.5.5.

**Comment by dcousens** [comment]
Added 3ee8b81 in the spirit of #384, which probably should have been in `1.5.5`.

Published as `1.5.6`.

**Comment by dcousens** [comment]
Before https://github.com/bitcoinjs/bitcoinjs-lib/pull/403 can be merged, a deprecation must be added for `ecdsa.verifyRaw`.

**Comment by dcousens** [comment]
@jsantirso see 87470de for example of tests.

**Comment by dcousens** [comment]
Unmerged:

#381 - Deprecations only
#403 - Deprecations only

**Comment by dcousens** [comment]
Unmerged:

https://github.com/bitcoinjs/bitcoinjs-lib/pull/420 - Deprecations only

**Comment by dcousens** [comment]
Unmerged:

#381 - Deprecations only
#401 - Deprecations only
#403 - Deprecations only
#418
#420 - Deprecations only
#423
#425 - Deprecations only

**Comment by dcousens** [comment]
Cherry picked (and merged): https://github.com/bitcoinjs/bitcoinjs-lib/pull/447

Published as `1.5.8`.

**Comment by dcousens** [comment]
Added deprecations for https://github.com/bitcoinjs/bitcoinjs-lib/pull/381 in f0a9624
Added stricter DER compliance (aka https://github.com/bitcoinjs/bitcoinjs-lib/pull/423/files) in 1de087f

**Comment by dcousens** [comment]
@weilu thoughts on the remaining deprecations that weren't added:

 - [ ] #401 - `Address -> address`,  any added warning would very extensive
 - [ ] #420 - removal of `ecdsa`,  difficult to add a user only deprecation,  extensively used would be a bit much
 - [ ] #425 - network detection,  probably not impossible,  just warn if no `networks` passed in and the network isn't `bitcoin`

**Pull request closed without merging**
