### PR TITLE
rm getAddress

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by dcousens** [comment]
Part of https://github.com/bitcoinjs/bitcoinjs-lib/issues/1017

**Comment by dcousens** [comment]
@junderw good to merge,  removal of `getAddress` only for now,  payments PR will be separate

**Comment by junderw** [comment]
Could you change requires to use const instead of let?

regex replace `let(\s+\S+\s+=\s+require\('[^']+'\))` with `const$1`

**Comment by dcousens** [comment]
@junderw I intend to do that in a mass PR after this stage.  For now,  I'm changing to `let` on anything I touch.

**Comment by takahser** [comment]
how can we get testnet addresses after this merge? when using `payments.p2pkh`, a `p2pkh` address is returned, rather than a testnet address (starting with `m` or `n`)

**Comment by junderw** [comment]
@takahser pass the testnet network.

**Pull request merged**
