### PR TITLE
README: fix brainwallet url

### PR DESCRIPTION
**Pull request by hisener**

### CODE REVIEW

**Comment by dcousens** [comment]
To be honest,  since they are still using `v0.1.3`,  which is highly out-dated and missing a lot of improvements (even bug fixes),  I'm not sure if we should continue saying they are actually using *this* library.

Thoughts @jprichardson ?

**Comment by hisener** [comment]
We can delete it or update URL.

I have also checked other projects.

**Comment by jprichardson** [comment]
Agreed @dcousens.

**Comment by hisener** [comment]
@jprichardson deleted.

**Comment by dcousens** [comment]
Thanks @hisener :+1:

**Pull request merged**
