### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by dcousens**
@jprichardson  / @weilu  please ACK before merge/publish.

Remaining (non-dependent) changes for publish:

* [x] Need to fix https://github.com/bitcoinjs/bitcoinjs-lib/issues/347

### CODE REVIEW

**Comment by dcousens** [comment]
ping @kyledrake, are you up for generating some PR around this?

**Comment by dcousens** [comment]
It may be worth mentioning the use of https://github.com/bitcoinjs/bitcoinjs-lib/issues/452 as well as part of a development change?  It doesn't directly affect the API,  but, it people might still be interested.

**Comment by jprichardson** [comment]
ACK. Very glad to see `CHANGELOG.md`.

**Comment by dcousens** [comment]
@weilu I might get you to POST ACK so we can merge this ASAP.

**Comment by dcousens** [comment]
Published as `2.0.0`.

Might be worth doing some PR around this still,  or not.  Thoughts?
In any case should clean up the [github site](https://github.com/bitcoinjs/bitcoinjs.github.com/issues/5).

Who owns that DNS btw?

**Comment by kyledrake** [comment]
@justmoon owns bitcoinjs.org, I don't control it.

I'm happy to do an announcement! I'll need to review the changes so I know what to write up.

**Pull request merged**
