### PR TITLE
index: stop exposing ecdsa

### PR DESCRIPTION
**Pull request by dcousens**
In preparation of #394.

### CODE REVIEW

**Comment by jprichardson** [comment]
It's not clear to me why we would want to do this at this point? Shouldn't we get #394 resolved first and then do this?

**Comment by dcousens** [comment]
@jprichardson the idea is that we can iterate on #394 without worrying about interrupting the public API.

**Comment by weilu** [comment]
LGTM. Please add deprecation warning on 1.x branch though.

**Comment by dcousens** [comment]
@jprichardson if you have further concerns with this,  please bring them up ASAP.

**Comment by jprichardson** [comment]
The problem is that `ECDSA` shouldn't have exposed the `ECC` primitives. (I guess a case could be made for performance) But given that's what we have now, I understand the reasoning behind this PR.

**Pull request merged**
