### PR TITLE
v2.2.0

### PR DESCRIPTION
**Pull request by dcousens**
ping @jprichardson @rubensayshi

### CODE REVIEW

**Comment by dcousens** [comment]
ping @fanatid ACK on all changes?

**Comment by dcousens** [comment]
@rubensayshi see the error received from integration tests:

>  1) bitcoinjs-lib (advanced) can create transactions using OP_CHECKLOCKTIMEVERIFY "before each" hook for "where Alice and Bob can redeem at any time":
     Expected Object, got String ""

This happens to me all the time in production where I use the BlockTrail CB API.  Could you please look into it? :+1:

**Comment by jprichardson** [comment]
ACK

**Comment by dcousens** [comment]
@rubensayshi I'm going to refresh the tests.   Please fix that issue though :+1:

**Comment by dcousens** [comment]
Published as `2.2.0`

**Pull request merged**
