### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dcousens**
See changes

### CODE REVIEW

**Comment by junderw** [comment]
We should add:

1. GPG sign your commits.
2. Or else the person reviewing will co-author and sign with their GPG key (this should be done right before merging, after the author rebases / squashes as instructed.) (https://help.github.com/articles/creating-a-commit-with-multiple-authors/) and (https://help.github.com/articles/signing-commits-using-gpg/) respectively.
3. Github signed commits (if you make commit through Web UI currently Github will sign your commit.) are fine.

**Comment by dcousens** [comment]
(@junderw can you add that? I sourced https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md for inspiration at times)

**Comment by dcousens** [comment]
We have branch protection in place... but it'd be nice if we could remove the ability to simply switch-it-off in the settings...

Any ideas?

**Comment by junderw** [comment]
hmmmmmmmm.....

If we restrict master to PR merges only, the master HEAD should always be a merge commit...

I wonder if there's some sort of setting file (ie. .gitignore) that will allow for some sort of pre-hook for git push... not allowing push (locally) if the HEAD commit msg doesn't start with "Merge..." etc.

git is deep, so I wouldn't be surprised if there were such a thing.

**Pull request merged**
