### PR TITLE
v4.0.2 + CHANGELOG

### PR DESCRIPTION
**Pull request by dcousens**
Added changelog and version update

### CODE REVIEW

**Comment by dcousens** [comment]
(if you are around @jprichardson,   please `npm publish`)

**Comment by jprichardson** [comment]
Tried to publish, but I don't have permissions on the package.

**Comment by dcousens** [comment]
@jprichardson permissions added explicitly.
For whatever reason the `bitcoinjs-lib` package is not under the `bitcoin-js` npm organization...

**Comment by dcousens** [comment]
@fanatid you might be able to add it now that I've added you?

**Comment by dcousens** [comment]
Published as `v4.0.2`

**Pull request merged**
