### PR TITLE
Use equal and reverse for buffer from bufferutils

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by dcousens** [comment]
The point was that we are always trying to remove/deprecate `bufferutils`.

**Comment by dcousens** [comment]
@fanatid I'd rather you just inline `bufferReverse` operations,  not use `bufferutils`.
Make that change and we'll merge :+1: (didn't realise the performance difference was so significant).

**Comment by fanatid** [comment]
@dcousens I didn't know that you trying remove `bufferutils`.
Why don't you add this point to https://github.com/bitcoinjs/bitcoinjs-lib/issues/508 ?

**Comment by dcousens** [comment]
@fanatid it was a general push,  and not something that may be possible for `3.0.0`.

**Pull request merged**
