### PR TITLE
Remove of pushOnly, added toStack

### PR DESCRIPTION
**Pull request by dcousens**
Non-breaking change as *pushOnly wasn't released yet.

### CODE REVIEW

**Comment by afk11** [comment]
Looks good, though on review https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#push-operators mentions OP_1NEGATE which is missed in `compile`, so compile(toStack()) mightn't always hold. Annoyingly, it's 0x81 on the stack so it's a special case to be added to compile if we're bothered.

**Comment by dcousens** [comment]
> compile(toStack()) mightn't always hold

What do you mean by that?

**Comment by afk11** [comment]
The current bscript.compile is going to end up encoding OP_1NEGATE as 0x0181, instead of using it's minimal encoding of 0x4f, so `compile` needs something to support that.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/732

**Pull request closed without merging**
