### PR TITLE
Update bitcoinforkjs lib to 3.3.1

### PR DESCRIPTION
**Pull request by Melvillian**
We need this for @arik-so's additions

8f9b3443d2b15deaa8762e266f6c60f6e7e6762a
5508e26469316aae9aaf903b734691ad7240d97a

so I figured I'd upgrade it to the latest while I'm at it.

### CODE REVIEW

**Comment by fanatid** [comment]
This is too big.
Maybe will better set destination branch as master and there will be changes for BCH & BTG?

**Comment by Melvillian** [comment]
@fanatid I can make a PR for merging the `opt-in-bitcoincash-sighash` branch onto the `3.3.1` release tag, but then which branch should I merge that onto? I'd like to keep a single branch for accumulating all hardfork-related logic, like `opt-in-bitcoincash-sighash` is doing.

**Comment by dabura667** [comment]
https://github.com/dabura667/bitcoinjs-lib/tree/forks331

@Melvillian Here you go.

**Comment by dabura667** [comment]
This was generated by the following commands.

```bash
git fetch bitcoinjs #note: my git folder has bitcoinjs as the remote name for the upstream. most likely you'll use "upstream" or whatever you named your remote.
git checkout bitcoinjs/opt-in-bitcoincash-sighash 
git checkout -b forks331
git rebase v3.3.1
# CONFLICT IN transaction_builder.js (I just chose the latter commit's fork)
# changed file and saved.
git add src/transaction_builder.js 
git rebase --continue
# CONFLICT IN package.json (I just chose the latter commit's fork)
# changed file and saved.
git add package.json 
git rebase --continue
git push dabura667 forks331 #I name all my remotes, even my own, by username
```

**Comment by dabura667** [comment]
In general, when you have a branch based on a old commit, and you want to make it base on a newer version, it is better to take the branched off commits and rebase them on the newer version rather than trying to merge all the commits from the old base to the new version into the branch.

```
      1a -- 2a -- 3a -- 4a(opt-in-sighash)
    / 
old -- 1 -- 2 -- 3 -- 4 ... ... ... ... ... ... ... ... ... ... -- 75(v3.3.1)
# instead of trying to merge 75 commits into the 4 branched off the old... take the four old commits and make a new pull request against v3.3.1 and we can just overwrite opt-in-sighash branch with your PR branch.
```

**Comment by dcousens** [comment]
It appears to have been rebased in https://github.com/bitcoinjs/bitcoinjs-lib/pull/937

**Pull request closed without merging**
