### PR TITLE
varstruct - WIP

### PR DESCRIPTION
**Pull request by fanatid**
[varstruct](https://github.com/dominictarr/varstruct/) for encode/decode blocks/txs?

### CODE REVIEW

**Comment by dcousens** [comment]
Will review soon :)

**Comment by fanatid** [comment]
@dcousens please check it, I want to know you opinion about this.
I fixed `varstruct` and now `fromBuffer` works fine. `toBuffer` doesn't work because `txOut` can have `valueBuffer` instead `value` (I don't know how handle it, may be create custom codec...).

@mappum since same structures are used in [bitcoin-protocol](https://github.com/mappum/bitcoin-protocol) maybe make sense create package `bitcoin-struct-tx-block` or two `bitcoin-tx-struct` and `bitcoin-block-struct`?

**Comment by mappum** [comment]
Maybe we should just make one `bitcoin-struct` package with all the structs in it?

**Comment by fanatid** [comment]
Sorry, what do you mean under *all* ? `tx` and `block` ?

**Comment by fanatid** [comment]
ping

**Comment by mappum** [comment]
I was thinking there might be other structs we might want to include, such as merkleblocks and full blocks (although those are not used by bitcoinjs).

**Comment by fanatid** [comment]
Looks like not actual right now, hope [varstruct](https://github.com/dominictarr/varstruct/) will be used in https://github.com/bitcoinjs/bitcoinjs-lib/issues/508

**Comment by dcousens** [comment]
@fanatid this looks really good :+1:

**Comment by dcousens** [comment]
`bitcoin-structs` might work,  assuming we just put all the basic POD types in there.

`Transaction`, `Block`?  Any others?

**Comment by fanatid** [comment]
or move messages from `bitcoin-protocol` to `bitcoin-protocol-messages` and use tx, block from there
https://github.com/mappum/bitcoin-protocol/blob/10d67127c89ed1928094be84375f70dfef0a43b3/src/messages.js

**Comment by dcousens** [comment]
@fanatid looks good to me. 
Though that would make https://github.com/bitcoinjs/bitcoinjs-lib/pull/440 either impossible, or something we'd need to do in lockstep with @mappum's `bitcoin-protocol`.

**Comment by dcousens** [comment]
Maybe @mappum we could move `bitcoin-protocol` to the bitcoinjs-org,  you'd still be lead contributor, but then it would be clear that the repository is linked (and hence in lockstep)?

**Comment by fanatid** [comment]
@dcousens if you wanted to move `bitcoin-protocol` you probably should do same with [bitcoin-net](https://github.com/mappum/bitcoin-net)

**Comment by dcousens** [comment]
Well,  that is up to @mappum

**Comment by dcousens** [comment]
I started playing with this @fanatid,  and ran into issues with `valueBuffer` edge cases.
I'd have to make a custom `encode`/`decode` that handled both cases (`Buffer` and `Number`).

**Comment by dcousens** [comment]
Closing for now

**Comment by dcousens** [comment]
Still covered by https://github.com/bitcoinjs/bitcoinjs-lib/issues/513

**Pull request closed without merging**
