### PR TITLE
Fixed Segwit links

### PR DESCRIPTION
**Pull request by wmpedersen**
The links were redirecting to 404 - I've modified them so they adhere to the beginning of the respective Segwit unit tests.This pull is in reference to Issue #872

### CODE REVIEW

**Comment by wmpedersen** [comment]
Perhaps this is being dealt with already, I see an issue #872 which addresses this.

**Comment by wmpedersen** [comment]
I found some more links in the Readme that were moved by the addition of the Segwit unit tests. ff61de9 covers everything in the file so far.

**Comment by afk11** [comment]
Almost worth having a script to generate it at release time, and a travis test to check.. It's unfortunate how prone to rot documentation like it can be, especially when line numbers are involved :P

**Comment by dabura667** [comment]
IMO links should always point to a commit based tree of the file. Will never budge. :-)

**Comment by dcousens** [comment]
@dabura667 I did that,  it didn't help the code rot situation.

Dead-links are at least obvious to users.

> Almost worth having a script to generate it at release time

These links were actually generated... it appears my regex foo failed though.

**Pull request merged**
