### PR TITLE
adds .npmignore

### PR DESCRIPTION
**Pull request by dcousens**
Any comments appreciated.  

Listening for a response to https://github.com/dominictarr/sha.js/issues/5 as well.

### CODE REVIEW

**Comment by fanatid** [comment]
@dcousens `jshint.json` now is excess
Why not use `files` in `package.json`? Have nothing against `.npmignore`, just a curious.

**Comment by dcousens** [comment]
@fanatid PR welcome.  Agreed on all points.

**Comment by fanatid** [comment]
@dcousens don't you mind if I also change keys order in package.json with order in [package.json doc](https://docs.npmjs.com/files/package.json)?

**Comment by dcousens** [comment]
@fanatid sure?  Is it necessary though?

**Comment by fanatid** [comment]
@dcousens it isn't necessary, just personal preference

**Comment by dcousens** [comment]
I don't really care what order.  I just want it consistent across all the `bitcoinjs/` projects (and maybe even mine `dcousens/` haha).
Whatever you change,  just,  consistency :+1: .

**Comment by fanatid** [comment]
.npmignore/files PR: #542
I also don't care about order, just want consistently everywhere. Since I use order from package.json docs, I trying do this everywhere :laughing:

**Pull request merged**
