### PR TITLE
txb: do not classify blank input scripts as nonstandard

### PR DESCRIPTION
**Pull request by dcousens**
Ref https://github.com/bitcoinjs/bitcoinjs-lib/issues/817

### CODE REVIEW

**Comment by dcousens** [comment]
ping @blkmaarx

**Comment by dcousens** [comment]
Post merge ACKs appreciated...

**Comment by runn1ng** [comment]
hm, what is empty input useful for in transactionbuilder?

**Comment by runn1ng** [comment]
Oh I see the bug report.

Whew, transactionbuilder is pretty complex now. ACK

**Comment by wattoosohaib9-tech** [comment]
L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy

**Pull request merged**
