### PR TITLE
Transaction: add getWitnessId (returning buffer)

### PR DESCRIPTION
**Pull request by afk11**
As per #715 I've separated out getWitnessId. I went with returning a Buffer this time, converting the id to hex by convention seems to be a convenience measure.. 

Useful to protocol implementors who wish to verify witness commitments, so should be available in some shape or form (commitment specification states that the leaves of the Merkle tree are the wtxid, not the witness buffer)

### CODE REVIEW

**Comment by dcousens** [comment]
IMHO, not `3.0.0`

**Comment by dcousens** [comment]
NACK for now, lets re-open in `3.1.0`,  if needed?

**Comment by afk11** [comment]
Why not? seems it's deciding for people what parts of the protocol to implement?

**Comment by dcousens** [comment]
> verify witness commitments

Maybe a test case for this would be good :+1:

**Comment by afk11** [comment]
That could be fun actually, let me look at the witness commitment templates & verification, see if I ca

**Comment by dcousens** [comment]
Going to close this in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/722,  which,  if this is needed, will be added there instead.

But I suspect it won't be needed at all.

**Pull request closed without merging**
