### PR TITLE
fix input classification bug

### PR DESCRIPTION
**Pull request by arik-so**
In some rare cases, transactions input types will get classified incorrectly. Script hash inputs will be classified as nonstandard. This change fixes that.

### CODE REVIEW

**Comment by dcousens** [comment]
Can you please add test fixtures?

**Comment by afk11** [comment]
I'd love to see a snippet of how this came about. TransactionBuilder.fromTransaction()? or just by calling the methods yourself?

Whether it's as simple as this fix, or if we have other input handling problems would be useful to know!

**Comment by arik-so** [comment]
Hi @dcousens and @afk11, I updated the pull request to add a transaction that has several examples of where the input classification would previously have been broken, and one input that remains unaffected. I hope the way I built the unit test is ok.

**Comment by dcousens** [comment]
Nice spot @arik-so!  I think the problem is rooter deeper than that though... check https://github.com/bitcoinjs/bitcoinjs-lib/pull/898

**Comment by arik-so** [comment]
I agree, @dcousens, the classification should be order-agnostic. If the other PR works, perhaps simply keeping the unit test changes from this one would make sense. And @junderw, I added the spaces, as requested.

**Comment by dcousens** [comment]
@arik-so if you could add your unit test changes by submitting a PR to the `bitcoinjs:fixes` branch,  that'd be awesome :+1:

**Comment by arik-so** [comment]
Sure thing! https://github.com/bitcoinjs/bitcoinjs-lib/pull/900

**Comment by dcousens** [comment]
closing in favour of #898

**Pull request closed without merging**
