### PR TITLE
Adding Transaction.prototype.isCoinbase

### PR DESCRIPTION
**Pull request by runn1ng**
A simple function that says if a given tx is coinbase tx or not

### CODE REVIEW

**Comment by dcousens** [comment]
Needs tests :+1:

**Comment by dcousens** [comment]
And rebase

**Comment by jprichardson** [comment]
I'm not strictly opposed to this, but I'm wondering if it's really worth the extra method. IDK

> Needs tests 

:+1:

**Comment by dcousens** [comment]
I've seen it in other libraries,  but whenever I thought I'd need it,  I was mistaken.  So I'm not sure what the practical use of such a function is.

**Comment by fanatid** [comment]
Am I skip something? I don't remember that coinbase tx should contain exactly 1 input.
@runn1ng except zero hash you also should check that output index is 0xFFFFFFFF

**Comment by dcousens** [comment]
@fanatid I had that same question,  it is mentioned ad-hoc in the wiki: https://en.bitcoin.it/wiki/Protocol_rules / https://en.bitcoin.it/wiki/Transaction#Generation,  but I'll probably confirm it in the reference implementation before I merge.

**Comment by runn1ng** [comment]
Ok, will add tests later and look at all the other stuff you mentioned.

**Comment by dcousens** [comment]
ping @runn1ng

**Comment by dcousens** [comment]
@fanatid  reference for the [consensus rules](https://github.com/bitcoin/bitcoin/blob/86b800c6a299455580fe76e5fb43218f0222e179/src/main.cpp#L3262-L3267) and [core implementation](https://github.com/bitcoin/bitcoin/blob/a9c8b744e8875785ff9a3768df3517b2d9ed7a36/src/primitives/transaction.h#L269-L272).

**Comment by dcousens** [comment]
Closing in favour of #578

**Comment by runn1ng** [comment]
I am very sorry for ignoring this, I was really busy last month. So glad you merged this.

**Comment by dcousens** [comment]
No worries @runn1ng,  I made sure to include your commit so as to hopefully not steal your thunder :+1:

**Pull request closed without merging**
