### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by dcousens**
Might be worth adding further notes RE `TransactionBuilder` support...

Thanks @afk11 for the baseline work done in the CHANGELOG;  and for so much of the segregated witness work.

### CODE REVIEW

**Comment by dcousens** [comment]
Tests only failing due to https://github.com/bitcoinjs/bitcoinjs-lib/issues/767

**Comment by dcousens** [comment]
Rebased and now tests are passing

**Comment by dcousens** [comment]
If possible,  I want to merge this within 8 hours. @afk11 @fanatid

**Comment by afk11** [comment]
Reviewing now!

**Comment by dcousens** [comment]
Published as https://github.com/bitcoinjs/bitcoinjs-lib/releases/tag/v3.0.0

**Pull request merged**
